import pandas as pd
import os
import re

fpath = "google_analytics/"

uniqueid_map = {
    "Ralph Norman: (United States)" : "Norman SC-5",
    "Randy Weber: (United States)" : "Weber TX-14",
    "Brian Babin: (United States)" : "Babin TX-36",
    "Greg Steube: (United States)" : "Steube FL-17",
    "Debbie Lesko: (United States)" : "Lesko AZ-8",
    "Ronny Jackson: (United States)" : "Jackson TX-13",
    "Jeff Duncan: (United States)" : "Duncan SC-3",
    "Mary Miller: (United States)" : "Miller IL-15",
    "Bill Posey: (United States)" : "Posey FL-8",
    "Bob Good: (United States)" : "Good VA-5",
    "Byron Donalds: (United States)" : "Donalds FL-19",
    "Scott Perry: (United States)" : "Perry PA-10",
    "Mariannette Miller-Meeks: (United States)" : "Miller-Meeks IA-1",
    "Glenn Grothman: (United States)" : "Grothman WI-6",
    "Tracey Mann: (United States)" : "Mann KS-1",
    "Doug LaMalfa: (United States)" : "LaMalfa CA-1",
    "Doug Lamborn: (United States)" : "Lamborn CO-5",
    "Elise Stefanik: (United States)" : "Stefanik NY-21",
    "John Rutherford: (United States)": "Rutherford FL-5",
    "Tom Tiffany: (United States)": "Tiffany WI-7",
    "Paul Gosar: (United States)": "Gosar AZ-9",
    "Lauren Boebert: (United States)": "Boebert CO-3",
    "Scott Franklin: (United States)": "Franklin FL-18",
    "Rick Crawford: (United States)": "Crawford AR-1",
    "Claudia Tenney: (United States)": "Tenney NY-24",
    "Ben Cline: (United States)": "Cline VA-6",
    "Andy Biggs: (United States)": "Biggs AZ-5",
    "Diana Harshbarger: (United States)": "Harshbarger TN-1",
    "Kat Cammack: (United States)": "Cammack FL-3",
    "Buddy Carter: (United States)": "Carter GA-1",
    "Brian Mast: (United States)": "Mast FL-21",
    "Jeff Van Drew: (United States)": "Van Drew NJ-2",
    "Michael Guest: (United States)": "Guest MS-3",
    "Jim Banks: (United States)": "Banks IN-3",
    "Barry Moore: (United States)": "Moore AL-2",
    "Alex Mooney: (United States)": "Mooney WV-2",
    "Rick Allen: (United States)": "Allen GA-12",
    "Guy Reschenthaler: (United States)": "Reschenthaler PA-14",
    "Dan Bishop: (United States)": "Bishop NC-8",
    "Tom Emmer: (United States)": "Emmer MN-6",
    "Ashley Hinson: (United States)": "Hinson IA-2",
    "Lance Gooden: (United States)": "Gooden TX-5",
    "Richard Hudson: (United States)": "Hudson NC-9",
    "Michael Cloud: (United States)": "Cloud TX-27",
    "Pat Fallon: (United States)": "Fallon TX-4",
    "Mike Johnson: (United States)": "Johnson LA-4",
    "Dan Crenshaw: (United States)": "Crenshaw TX-2",
    "Jake LaTurner: (United States)": "LaTurner KS-2",
    "Dan Meuser: (United States)": "Meuser PA-9",
    "Dan Newhouse: (United States)": "Newhouse WA-4",
    "Mike Kelly: (United States)": "Kelly PA-16",
    "William Timmons: (United States)": "Timmons SC-4",
    "John Moolenaar: (United States)": "Moolenaar MI-2",
    "Burgess Owens: (United States)": "Owens UT-4",
    "David Rouzer: (United States)": "Rouzer NC-7",
    "August Pfluger: (United States)": "Pfluger TX-11",
    "Matt Gaetz: (United States)": "Gaetz FL-1",
    "Michael Waltz: (United States)": "Waltz FL-6",
    "Jim Baird: (United States)": "Baird IN-4",
    "Lisa McClain: (United States)": "McClain MI-9",
    "Michael Bost: (United States)": "Bost IL-12",
    "Greg Murphy: (United States)": "Murphy NC-3",
    "Pete Sessions: (United States)": "Sessions TX-17",
    "Gus Bilirakis: (United States)": "Bilirakis FL-12",
    "Pete Stauber: (United States)": "Stauber MN-8",
    "Ann Wagner: (United States)": "Wagner MO-2",
    "Michael Burgess: (United States)": "Burgess TX-26",
    "Joe Wilson: (United States)": "Wilson SC-2",
    "Ken Buck: (United States)": "Buck CO-4",
    "John Joyce: (United States)": "Joyce PA-13",
    "Randy Feenstra: (United States)": "Feenstra IA-4",
    "Tom McClintock: (United States)": "McClintock CA-5",
    "Warren Davidson: (United States)": "Davidson OH-8",
    "Matt Rosendale: (United States)": "Rosendale MT-2",
    "Don Bacon: (United States)": "Bacon NE-2",
    "Clay Higgins: (United States)": "Higgins LA-3",
    "Scott DesJarlais: (United States)": "DesJarlais TN-4", 
    "Jake Ellzey: (United States)": "Ellzey TX-6",
    "Chip Roy: (United States)": "Roy TX-21",
    "Jerry L. Carl: (United States)": "Carl AL-1",
    "Troy Balderson: (United States)": "Balderson OH-12",
    "Beth Van Duyne: (United States)": "Van Duyne TX-24",
    "Bob Latta: (United States)": "Latta OH-5",
    "Andrew Clyde: (United States)": "Clyde GA-9",
    "Andrew Garbarino: (United States)": "Garbarino NY-2",
    "Brad Wenstrup: (United States)": "Wenstrup OH-2",
    "Rob Wittman: (United States)": "Wittman VA-1",
    "Maria Elvira Salazar: (United States)": "Salazar FL-27",
    "Stephanie Bice: (United States)": "Bice OK-5",
    "Bruce Westerman: (United States)": "Westerman AR-4",
    "Dusty Johnson: (United States)": "Johnson SD",
    "Bill Huizenga: (United States)": "Huizenga MI-4",
    "John Rose: (United States)": "Rose TN-6",
    "Ken Calvert: (United States)": "Calvert CA-41",
    "Austin Scott: (United States)": "Scott GA-8",
    "Trent Kelly: (United States)": "Kelly MS-1",
    "Kevin Hern: (United States)": "Hern OK-1",
    "David Kustoff: (United States)": "Kustoff TN-8",
    "Michelle Fischbach: (United States)": "Fischbach MN-7",
    "Larry Bucshon: (United States)": "Bucshon IN-8",
    "Jason Smith: (United States)": "Smith MO-8",
    "Glenn Thompson: (United States)": "Thompson PA-15",
    "Carlos A. Giménez: (United States)": "Gimenez FL-28",
    "Jodey Arrington: (United States)": "Arrington TX-19",
    "Cathy McMorris Rodgers: (United States)": "McMorris Rodgers WA-5",
    "Neal Dunn: (United States)": "Dunn FL-2",
    "Daniel Webster: (United States)": "Webster FL-11",
    "Russ Fulcher: (United States)": "Fulcher ID-1",
    "Nancy Mace: (United States)": "Mace SC-1",
    "Blaine Luetkemeyer: (United States)": "Luetkemeyer MO-3",
    "Tim Walberg: (United States)": "Walberg MI-5",
    "Nicole Malliotakis: (United States)": "Malliotakis NY-11",
    "Chris Stewart: (United States)": "Stewart UT-2",
    "Tim Burchett: (United States)": "Burchett TN-2",
    "Jack Bergman: (United States)": "Bergman MI-1",
    "Andy Barr: (United States)": "Barr KY-6",
    "French Hill: (United States)": "Hill AR-2",
    "Robert Aderholt: (United States)": "Aderholt AL-4",
    "Barry Loudermilk: (United States)": "Loudermilk GA-11",
    "David Valadao: (United States)": "Valadao CA-22",
    "Jay Obernolte: (United States)": "Obernolte CA-23",
    "Steve Womack: (United States)": "Womack AR-3",
    "Drew Ferguson: (United States)": "Ferguson GA-3",
    "Julia Letlow: (United States)": "Letlow LA-5",
    "Bryan Steil: (United States)": "Steil WI-1",
    "David Schweikert: (United States)": "Schweikert AZ-1",
    "Chuck Fleischmann: (United States)": "Fleischmann TN-3",
    "Virginia Foxx: (United States)": "Foxx NC-5",
    "Mark Green: (United States)": "Green TN-7",
    "Tom Cole: (United States)": "Cole OK-4",
    "Blake Moore: (United States)": "Moore UT-1",
    "Gary Palmer: (United States)": "Palmer AL-6",
    "Garret Graves: (United States)": "Graves LA-6",
    "Darrell Issa: (United States)": "Issa CA-48",
    "Ron Estes: (United States)": "Estes KS-4",
    "Brett Guthrie: (United States)": "Guthrie KY-2",
    "Mike Gallagher: (United States)": "Gallagher WI-8",
    "Mario Díaz-Balart: (United States)": "Diaz-Balart FL-26",
    "Marjorie Taylor Greene: (United States)": "Greene GA-14",
    "Troy Nehls: (United States)": "Nehls TX-22",
    "Carol Miller: (United States)": "Miller WV-1",
    "Cliff Bentz: (United States)": "Bentz OR-2",
    "Lloyd Smucker: (United States)": "Smucker PA-11",
    "Morgan Griffith: (United States)": "Griffith VA-9",
    "Chris Smith: (United States)": "Smith NJ-4",
    "Michael McCaul: (United States)": "McCaul TX-10",
    "Mike Rogers: (United States)": "Rogers AL-3",
    "Kelly Armstrong: (United States)": "Armstrong ND",
    "Jim Jordan: (United States)": "Jordan OH-4",
    "Vern Buchanan: (United States)": "Buchanan FL-16",
    "Mike Garcia: (United States)": "Garcia CA-27",
    "James Comer: (United States)": "Comer KY-1",
    "John Curtis: (United States)": "Curtis UT-3",
    "Michelle Park Steel: (United States)": "Steel CA-45",
    "Young Kim: (United States)": "Kim CA-40",
    "Darin LaHood: (United States)": "LaHood IL-16",
    "Greg Pence: (United States)": "Pence IN-6",
    "Brian Fitzpatrick: (United States)": "Fitzpatrick PA-1",
    "Mike Carey: (United States)": "Carey OH-15",
    "Victoria Spartz: (United States)": "Spartz IN-5",
    "Thomas Massie: (United States)": "Massie KY-4",
    "Steve Scalise: (United States)": "Scalise LA-1",
    "Tony Gonzales: (United States)": "Gonzales TX-23",
    "Mike Turner: (United States)": "Turner OH-10",
    "Mark Amodei: (United States)": "Amodei NV-2",
    "Mike Simpson: (United States)": "Simpson ID-2",
    "Patrick McHenry: (United States)": "McHenry NC-10",
    "Hal Rogers: (United States)": "Rogers KY-5",
    "Sam Graves: (United States)": "Graves MO-6",
    "Kay Granger: (United States)": "Granger TX-12",
    "Brad Finstad: (United States)": "Finstad MN-1",
    "Kevin McCarthy: (United States)": "McCarthy CA-20",
    "Mike Flood: (United States)": "Flood NE-1",
    "Rudy Yakym: (United States)": "Yakym IN-2",
    "Dale Strong: (United States)": "Strong AL-5",
    "Juan Ciscomani: (United States)": "Ciscomani AZ-6",
    "Eli Crane: (United States)": "Crane AZ-2",
    "John Duarte: (United States)": "Duarte CA-13",
    "Kevin Kiley: (United States)": "Kiley CA-3",
    "Vince Fong: (United States)": "Fong CA-20",
    "Greg Lopez: (United States)": "Lopez CO-4",
    "Aaron Bean: (United States)": "Bean FL-4",
    "Laurel Lee: (United States)": "Lee FL-15",
    "Anna Paulina Luna: (United States)": "Luna FL-13",
    "Cory Mills: (United States)": "Mills FL-7",
    "Mike Collins: (United States)": "Collins GA-10",
    "Rich McCormick: (United States)": "McCormick GA-6",
    "Erin Houchin: (United States)": "Houchin IN-9",
    "Zach Nunn: (United States)": "Nunn IA-3",
    "John James: (United States)": "James MI-10",
    "Mike Ezell: (United States)": "Ezell MS-4",
    "Mark Alford: (United States)": "Alford MO-4",
    "Ryan Zinke: (United States)": "Zinke MT-1",
    "Thomas Kean Jr.: (United States)": "Kean NJ-7",
    "Nick LaLota: (United States)": "LaLota NY-1",
    "Nick Langworthy: (United States)": "Langworthy NY-23",
    "Mike Lawler: (United States)": "Lawler NY-17",
    "Marcus Molinaro: (United States)": "Molinaro NY-19",
    "George Santos: (United States)": "Santos NY-3",
    "Chuck Edwards: (United States)": "Edwards NC-11",
    "David Joyce: (United States)": "Joyce OH-14",
    "Max Miller: (United States)": "Miller OH-7",
    "Michael Rulli: (United States)": "Rulli OH-6",
    "Josh Brecheen: (United States)": "Brecheen OK-2",
    "Lori Chavez-DeRemer: (United States)": "Chavez-Deremer OR-5",
    "Russell Fry: (United States)": "Fry SC-7",
    "Andy Ogles: (United States)": "Ogles TN-5",
    "Monica De La Cruz: (United States)": "De La Cruz TX-15",
    "Wesley Hunt: (United States)": "Hunt TX-38",
    "Morgan Luttrell: (United States)": "Luttrell TX-8",
    "Nathaniel Moran: (United States)": "Moran TX-1",
    "Keith Self: (United States)": "Self TX-3",
    "Celeste Maloy: (United States)": "Maloy UT-2",
    "Jen Kiggans: (United States)": "Kiggans VA-2",
    "Derrick Van Orden: (United States)": "Van Orden WI-3",
    "Harriet Hageman: (United States)": "Hageman WY-1",
}

def extract_num(text):
    return re.search(r'\d+', text).group(0)

files = os.listdir(fpath)
dfs = list()

for file in files:  
    df_tmp = pd.read_csv(fpath + file, skiprows = 2).drop(columns = 'Week').replace("<1","0.1").astype(float) # for numerical issues it is 0.1 instead of 0
    df_means = df_tmp.mean().reset_index()
    df_means['file'] = file
    df_means.columns = ['rep','average','file']
    dfs.append(df_means)

base_rep = 'Ralph Norman: (United States)'

df_base = dfs[0]
df_base['batch'] = df_base['file'].apply(extract_num).astype(int)
dfs_norm = [df_base]
df_base_avg = df_base[df_base['rep'] == base_rep]['average'].sum()

for i in range(1,len(dfs)):
    df_tmp = dfs[i]
    df_tmp['batch'] = df_tmp['file'].apply(extract_num).astype(int)
    df_curr_avg = df_tmp[df_tmp['rep'] == base_rep]['average'].sum()
    df_tmp = df_tmp[df_tmp['rep'] != base_rep]
    df_tmp['average'] = df_tmp['average'] * (df_base_avg / df_curr_avg)
    df_tmp['average'] = df_tmp['average'].fillna(0) 
    dfs_norm.append(df_tmp)

df_norm = pd.concat(dfs_norm, axis = 0) # this should sync up w the 118 dataframe rep order
df_norm = df_norm.reset_index()
df_norm = df_norm.sort_values(by = ['batch', 'index'])

#df_norm['uniqueid'] = uniqueids[:df_norm.shape[0]]
df_norm['uniqueid'] = df_norm['rep'].map(uniqueid_map)

print(df_norm.tail(55))
print("# reps:", df_norm.shape[0])

df_norm.to_csv("google_analytics.csv")
